version: '3.9'
services:
  db:
    platform: linux/amd64
    image: mysql:5.7.34
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: True
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
